ymlを直接編集
PS C:\Users\mar18\Desktop\Tech0\STEP_03\challenge\250523_Practical\frontend> git status
On branch main
On branch main
Your branch is up to date with 'origin/main'.
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
PS C:\Users\mar18\Desktop\Tech0\STEP_03\challenge\250523_Practical\frontend> git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .github/workflows/main_app-001-step3-1-suzuyu-node-32.yml

no changes added to commit (use "git add" and/or "git commit -a")
PS C:\Users\mar18\Desktop\Tech0\STEP_03\challenge\250523_Practical\frontend> git add .
PS C:\Users\mar18\Desktop\Tech0\STEP_03\challenge\250523_Practical\frontend> git commit -m "ymalの修正"
[main 495fb72] ymalの修正
 1 file changed, 14 insertions(+), 4 deletions(-)
PS C:\Users\mar18\Desktop\Tech0\STEP_03\challenge\250523_Practical\frontend> git push
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 611 bytes | 611.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/e10tech/practical_front.git
 ! [remote rejected] main -> main (refusing to allow an OAuth App to create or update workflow `.github/workflows/main_app-001-step3-1-suzuyu-node-32.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/e10tech/practical_front.git'